// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: url_shorter/v1/url_shorter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateUrlRequest represents the input parameters required to create a new short URL.
type CreateUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The original long URL to be shortened (required).
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// The custom short key for the short URL (optional).
	ShortKey string `protobuf:"bytes,2,opt,name=short_key,proto3" json:"short_key,omitempty"`
	// The business ID associated with the short URL (optional).
	BizId int64 `protobuf:"varint,3,opt,name=biz_id,proto3" json:"biz_id,omitempty"`
	// The expiration timestamp for the short URL (optional).
	ExpiredAt int64 `protobuf:"varint,4,opt,name=expired_at,proto3" json:"expired_at,omitempty"`
}

func (x *CreateUrlRequest) Reset() {
	*x = CreateUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shorter_v1_url_shorter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUrlRequest) ProtoMessage() {}

func (x *CreateUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shorter_v1_url_shorter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateUrlRequest) Descriptor() ([]byte, []int) {
	return file_url_shorter_v1_url_shorter_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateUrlRequest) GetShortKey() string {
	if x != nil {
		return x.ShortKey
	}
	return ""
}

func (x *CreateUrlRequest) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *CreateUrlRequest) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

// CreateUrlReply contains the generated short URL as a response.
type CreateUrlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The created short URL.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CreateUrlReply) Reset() {
	*x = CreateUrlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shorter_v1_url_shorter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUrlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUrlReply) ProtoMessage() {}

func (x *CreateUrlReply) ProtoReflect() protoreflect.Message {
	mi := &file_url_shorter_v1_url_shorter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUrlReply.ProtoReflect.Descriptor instead.
func (*CreateUrlReply) Descriptor() ([]byte, []int) {
	return file_url_shorter_v1_url_shorter_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUrlReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// JumpRequest represents the input parameters required to retrieve the long URL associated with a short URL.
type JumpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The short URL to be used for the lookup (required)..
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *JumpRequest) Reset() {
	*x = JumpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shorter_v1_url_shorter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JumpRequest) ProtoMessage() {}

func (x *JumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shorter_v1_url_shorter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JumpRequest.ProtoReflect.Descriptor instead.
func (*JumpRequest) Descriptor() ([]byte, []int) {
	return file_url_shorter_v1_url_shorter_proto_rawDescGZIP(), []int{2}
}

func (x *JumpRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// JumpReply contains the retrieved long URL as a response.
type JumpReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID associated with the short URL.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The original long URL associated with the short URL.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *JumpReply) Reset() {
	*x = JumpReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shorter_v1_url_shorter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JumpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JumpReply) ProtoMessage() {}

func (x *JumpReply) ProtoReflect() protoreflect.Message {
	mi := &file_url_shorter_v1_url_shorter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JumpReply.ProtoReflect.Descriptor instead.
func (*JumpReply) Descriptor() ([]byte, []int) {
	return file_url_shorter_v1_url_shorter_proto_rawDescGZIP(), []int{3}
}

func (x *JumpReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JumpReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_url_shorter_v1_url_shorter_proto protoreflect.FileDescriptor

var file_url_shorter_v1_url_shorter_proto_rawDesc = []byte{
	0x0a, 0x20, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x2f, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x7a, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x5f, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x69, 0x7a, 0x5f, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x22, 0x22, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x22, 0x1f, 0x0a, 0x0b, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x2d, 0x0a, 0x09, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x32, 0xe1, 0x01, 0x0a, 0x13, 0x55, 0x72, 0x6c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x2e, 0x75, 0x72, 0x6c,
	0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x75,
	0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x13, 0x3a, 0x01, 0x2a, 0x22, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x2f, 0x75, 0x72, 0x6c, 0x12, 0x5b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x1b, 0x2e, 0x75, 0x72, 0x6c, 0x5f,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x75, 0x6d, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x12, 0x09, 0x2f, 0x67, 0x6f, 0x2f, 0x7b,
	0x75, 0x72, 0x6c, 0x7d, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x70, 0x68, 0x70, 0x67, 0x61, 0x6f, 0x2f, 0x64, 0x75, 0x72, 0x6c, 0x5f, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x72, 0x6c, 0x5f, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_url_shorter_v1_url_shorter_proto_rawDescOnce sync.Once
	file_url_shorter_v1_url_shorter_proto_rawDescData = file_url_shorter_v1_url_shorter_proto_rawDesc
)

func file_url_shorter_v1_url_shorter_proto_rawDescGZIP() []byte {
	file_url_shorter_v1_url_shorter_proto_rawDescOnce.Do(func() {
		file_url_shorter_v1_url_shorter_proto_rawDescData = protoimpl.X.CompressGZIP(file_url_shorter_v1_url_shorter_proto_rawDescData)
	})
	return file_url_shorter_v1_url_shorter_proto_rawDescData
}

var file_url_shorter_v1_url_shorter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_url_shorter_v1_url_shorter_proto_goTypes = []interface{}{
	(*CreateUrlRequest)(nil), // 0: url_shorter.v1.CreateUrlRequest
	(*CreateUrlReply)(nil),   // 1: url_shorter.v1.CreateUrlReply
	(*JumpRequest)(nil),      // 2: url_shorter.v1.JumpRequest
	(*JumpReply)(nil),        // 3: url_shorter.v1.JumpReply
}
var file_url_shorter_v1_url_shorter_proto_depIdxs = []int32{
	0, // 0: url_shorter.v1.UrlShortenerService.CreateShortUrl:input_type -> url_shorter.v1.CreateUrlRequest
	2, // 1: url_shorter.v1.UrlShortenerService.GetRedirectURL:input_type -> url_shorter.v1.JumpRequest
	1, // 2: url_shorter.v1.UrlShortenerService.CreateShortUrl:output_type -> url_shorter.v1.CreateUrlReply
	3, // 3: url_shorter.v1.UrlShortenerService.GetRedirectURL:output_type -> url_shorter.v1.JumpReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_url_shorter_v1_url_shorter_proto_init() }
func file_url_shorter_v1_url_shorter_proto_init() {
	if File_url_shorter_v1_url_shorter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_url_shorter_v1_url_shorter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shorter_v1_url_shorter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUrlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shorter_v1_url_shorter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JumpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shorter_v1_url_shorter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JumpReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_url_shorter_v1_url_shorter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_shorter_v1_url_shorter_proto_goTypes,
		DependencyIndexes: file_url_shorter_v1_url_shorter_proto_depIdxs,
		MessageInfos:      file_url_shorter_v1_url_shorter_proto_msgTypes,
	}.Build()
	File_url_shorter_v1_url_shorter_proto = out.File
	file_url_shorter_v1_url_shorter_proto_rawDesc = nil
	file_url_shorter_v1_url_shorter_proto_goTypes = nil
	file_url_shorter_v1_url_shorter_proto_depIdxs = nil
}
