// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/phpgao/durl_backend/internal/data/ent/schema"
	"github.com/phpgao/durl_backend/internal/data/ent/tleaf"
	"github.com/phpgao/durl_backend/internal/data/ent/tshorturl"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tleafFields := schema.TLeaf{}.Fields()
	_ = tleafFields
	// tleafDescBizTag is the schema descriptor for biz_tag field.
	tleafDescBizTag := tleafFields[1].Descriptor()
	// tleaf.BizTagValidator is a validator for the "biz_tag" field. It is called by the builders before save.
	tleaf.BizTagValidator = tleafDescBizTag.Validators[0].(func(string) error)
	// tleafDescMaxID is the schema descriptor for max_id field.
	tleafDescMaxID := tleafFields[2].Descriptor()
	// tleaf.DefaultMaxID holds the default value on creation for the max_id field.
	tleaf.DefaultMaxID = tleafDescMaxID.Default.(int64)
	// tleafDescStep is the schema descriptor for step field.
	tleafDescStep := tleafFields[3].Descriptor()
	// tleaf.DefaultStep holds the default value on creation for the step field.
	tleaf.DefaultStep = tleafDescStep.Default.(int64)
	// tleafDescDesc is the schema descriptor for desc field.
	tleafDescDesc := tleafFields[4].Descriptor()
	// tleaf.DescValidator is a validator for the "desc" field. It is called by the builders before save.
	tleaf.DescValidator = tleafDescDesc.Validators[0].(func(string) error)
	// tleafDescVersion is the schema descriptor for version field.
	tleafDescVersion := tleafFields[5].Descriptor()
	// tleaf.DefaultVersion holds the default value on creation for the version field.
	tleaf.DefaultVersion = tleafDescVersion.Default.(int32)
	tshorturlFields := schema.TShortUrl{}.Fields()
	_ = tshorturlFields
	// tshorturlDescOrigin is the schema descriptor for origin field.
	tshorturlDescOrigin := tshorturlFields[2].Descriptor()
	// tshorturl.OriginValidator is a validator for the "origin" field. It is called by the builders before save.
	tshorturl.OriginValidator = func() func(string) error {
		validators := tshorturlDescOrigin.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(origin string) error {
			for _, fn := range fns {
				if err := fn(origin); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tshorturlDescVisit is the schema descriptor for visit field.
	tshorturlDescVisit := tshorturlFields[4].Descriptor()
	// tshorturl.DefaultVisit holds the default value on creation for the visit field.
	tshorturl.DefaultVisit = tshorturlDescVisit.Default.(int64)
	// tshorturlDescExpiredAt is the schema descriptor for expired_at field.
	tshorturlDescExpiredAt := tshorturlFields[7].Descriptor()
	// tshorturl.DefaultExpiredAt holds the default value on creation for the expired_at field.
	tshorturl.DefaultExpiredAt = tshorturlDescExpiredAt.Default.(int64)
}
