// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/phpgao/durl_backend/internal/data/ent/predicate"
	"github.com/phpgao/durl_backend/internal/data/ent/tshorturl"
)

// TShortUrlQuery is the builder for querying TShortUrl entities.
type TShortUrlQuery struct {
	config
	ctx        *QueryContext
	order      []tshorturl.OrderOption
	inters     []Interceptor
	predicates []predicate.TShortUrl
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TShortUrlQuery builder.
func (tuq *TShortUrlQuery) Where(ps ...predicate.TShortUrl) *TShortUrlQuery {
	tuq.predicates = append(tuq.predicates, ps...)
	return tuq
}

// Limit the number of records to be returned by this query.
func (tuq *TShortUrlQuery) Limit(limit int) *TShortUrlQuery {
	tuq.ctx.Limit = &limit
	return tuq
}

// Offset to start from.
func (tuq *TShortUrlQuery) Offset(offset int) *TShortUrlQuery {
	tuq.ctx.Offset = &offset
	return tuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tuq *TShortUrlQuery) Unique(unique bool) *TShortUrlQuery {
	tuq.ctx.Unique = &unique
	return tuq
}

// Order specifies how the records should be ordered.
func (tuq *TShortUrlQuery) Order(o ...tshorturl.OrderOption) *TShortUrlQuery {
	tuq.order = append(tuq.order, o...)
	return tuq
}

// First returns the first TShortUrl entity from the query.
// Returns a *NotFoundError when no TShortUrl was found.
func (tuq *TShortUrlQuery) First(ctx context.Context) (*TShortUrl, error) {
	nodes, err := tuq.Limit(1).All(setContextOp(ctx, tuq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tshorturl.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tuq *TShortUrlQuery) FirstX(ctx context.Context) *TShortUrl {
	node, err := tuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TShortUrl ID from the query.
// Returns a *NotFoundError when no TShortUrl ID was found.
func (tuq *TShortUrlQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = tuq.Limit(1).IDs(setContextOp(ctx, tuq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tshorturl.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tuq *TShortUrlQuery) FirstIDX(ctx context.Context) int64 {
	id, err := tuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TShortUrl entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TShortUrl entity is found.
// Returns a *NotFoundError when no TShortUrl entities are found.
func (tuq *TShortUrlQuery) Only(ctx context.Context) (*TShortUrl, error) {
	nodes, err := tuq.Limit(2).All(setContextOp(ctx, tuq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tshorturl.Label}
	default:
		return nil, &NotSingularError{tshorturl.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tuq *TShortUrlQuery) OnlyX(ctx context.Context) *TShortUrl {
	node, err := tuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TShortUrl ID in the query.
// Returns a *NotSingularError when more than one TShortUrl ID is found.
// Returns a *NotFoundError when no entities are found.
func (tuq *TShortUrlQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = tuq.Limit(2).IDs(setContextOp(ctx, tuq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tshorturl.Label}
	default:
		err = &NotSingularError{tshorturl.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tuq *TShortUrlQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := tuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TShortUrls.
func (tuq *TShortUrlQuery) All(ctx context.Context) ([]*TShortUrl, error) {
	ctx = setContextOp(ctx, tuq.ctx, "All")
	if err := tuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TShortUrl, *TShortUrlQuery]()
	return withInterceptors[[]*TShortUrl](ctx, tuq, qr, tuq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tuq *TShortUrlQuery) AllX(ctx context.Context) []*TShortUrl {
	nodes, err := tuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TShortUrl IDs.
func (tuq *TShortUrlQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if tuq.ctx.Unique == nil && tuq.path != nil {
		tuq.Unique(true)
	}
	ctx = setContextOp(ctx, tuq.ctx, "IDs")
	if err = tuq.Select(tshorturl.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tuq *TShortUrlQuery) IDsX(ctx context.Context) []int64 {
	ids, err := tuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tuq *TShortUrlQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tuq.ctx, "Count")
	if err := tuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tuq, querierCount[*TShortUrlQuery](), tuq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tuq *TShortUrlQuery) CountX(ctx context.Context) int {
	count, err := tuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tuq *TShortUrlQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tuq.ctx, "Exist")
	switch _, err := tuq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tuq *TShortUrlQuery) ExistX(ctx context.Context) bool {
	exist, err := tuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TShortUrlQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tuq *TShortUrlQuery) Clone() *TShortUrlQuery {
	if tuq == nil {
		return nil
	}
	return &TShortUrlQuery{
		config:     tuq.config,
		ctx:        tuq.ctx.Clone(),
		order:      append([]tshorturl.OrderOption{}, tuq.order...),
		inters:     append([]Interceptor{}, tuq.inters...),
		predicates: append([]predicate.TShortUrl{}, tuq.predicates...),
		// clone intermediate query.
		sql:  tuq.sql.Clone(),
		path: tuq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BizID int64 `json:"biz_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TShortUrl.Query().
//		GroupBy(tshorturl.FieldBizID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tuq *TShortUrlQuery) GroupBy(field string, fields ...string) *TShortUrlGroupBy {
	tuq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TShortUrlGroupBy{build: tuq}
	grbuild.flds = &tuq.ctx.Fields
	grbuild.label = tshorturl.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BizID int64 `json:"biz_id,omitempty"`
//	}
//
//	client.TShortUrl.Query().
//		Select(tshorturl.FieldBizID).
//		Scan(ctx, &v)
func (tuq *TShortUrlQuery) Select(fields ...string) *TShortUrlSelect {
	tuq.ctx.Fields = append(tuq.ctx.Fields, fields...)
	sbuild := &TShortUrlSelect{TShortUrlQuery: tuq}
	sbuild.label = tshorturl.Label
	sbuild.flds, sbuild.scan = &tuq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TShortUrlSelect configured with the given aggregations.
func (tuq *TShortUrlQuery) Aggregate(fns ...AggregateFunc) *TShortUrlSelect {
	return tuq.Select().Aggregate(fns...)
}

func (tuq *TShortUrlQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tuq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tuq); err != nil {
				return err
			}
		}
	}
	for _, f := range tuq.ctx.Fields {
		if !tshorturl.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tuq.path != nil {
		prev, err := tuq.path(ctx)
		if err != nil {
			return err
		}
		tuq.sql = prev
	}
	return nil
}

func (tuq *TShortUrlQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TShortUrl, error) {
	var (
		nodes = []*TShortUrl{}
		_spec = tuq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TShortUrl).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TShortUrl{config: tuq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(tuq.modifiers) > 0 {
		_spec.Modifiers = tuq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tuq *TShortUrlQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tuq.querySpec()
	if len(tuq.modifiers) > 0 {
		_spec.Modifiers = tuq.modifiers
	}
	_spec.Node.Columns = tuq.ctx.Fields
	if len(tuq.ctx.Fields) > 0 {
		_spec.Unique = tuq.ctx.Unique != nil && *tuq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tuq.driver, _spec)
}

func (tuq *TShortUrlQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tshorturl.Table, tshorturl.Columns, sqlgraph.NewFieldSpec(tshorturl.FieldID, field.TypeInt64))
	_spec.From = tuq.sql
	if unique := tuq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tuq.path != nil {
		_spec.Unique = true
	}
	if fields := tuq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tshorturl.FieldID)
		for i := range fields {
			if fields[i] != tshorturl.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tuq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tuq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tuq *TShortUrlQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tuq.driver.Dialect())
	t1 := builder.Table(tshorturl.Table)
	columns := tuq.ctx.Fields
	if len(columns) == 0 {
		columns = tshorturl.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tuq.sql != nil {
		selector = tuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tuq.ctx.Unique != nil && *tuq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tuq.modifiers {
		m(selector)
	}
	for _, p := range tuq.predicates {
		p(selector)
	}
	for _, p := range tuq.order {
		p(selector)
	}
	if offset := tuq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tuq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tuq *TShortUrlQuery) Modify(modifiers ...func(s *sql.Selector)) *TShortUrlSelect {
	tuq.modifiers = append(tuq.modifiers, modifiers...)
	return tuq.Select()
}

// TShortUrlGroupBy is the group-by builder for TShortUrl entities.
type TShortUrlGroupBy struct {
	selector
	build *TShortUrlQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tugb *TShortUrlGroupBy) Aggregate(fns ...AggregateFunc) *TShortUrlGroupBy {
	tugb.fns = append(tugb.fns, fns...)
	return tugb
}

// Scan applies the selector query and scans the result into the given value.
func (tugb *TShortUrlGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tugb.build.ctx, "GroupBy")
	if err := tugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TShortUrlQuery, *TShortUrlGroupBy](ctx, tugb.build, tugb, tugb.build.inters, v)
}

func (tugb *TShortUrlGroupBy) sqlScan(ctx context.Context, root *TShortUrlQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tugb.fns))
	for _, fn := range tugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tugb.flds)+len(tugb.fns))
		for _, f := range *tugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TShortUrlSelect is the builder for selecting fields of TShortUrl entities.
type TShortUrlSelect struct {
	*TShortUrlQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tus *TShortUrlSelect) Aggregate(fns ...AggregateFunc) *TShortUrlSelect {
	tus.fns = append(tus.fns, fns...)
	return tus
}

// Scan applies the selector query and scans the result into the given value.
func (tus *TShortUrlSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tus.ctx, "Select")
	if err := tus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TShortUrlQuery, *TShortUrlSelect](ctx, tus.TShortUrlQuery, tus, tus.inters, v)
}

func (tus *TShortUrlSelect) sqlScan(ctx context.Context, root *TShortUrlQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tus.fns))
	for _, fn := range tus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tus *TShortUrlSelect) Modify(modifiers ...func(s *sql.Selector)) *TShortUrlSelect {
	tus.modifiers = append(tus.modifiers, modifiers...)
	return tus
}
