// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TLeaf is the predicate function for tleaf builders.
type TLeaf func(*sql.Selector)

// TShortUrl is the predicate function for tshorturl builders.
type TShortUrl func(*sql.Selector)
