// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LeafColumns holds the columns for the "leaf" table.
	LeafColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "primary key"},
		{Name: "biz_tag", Type: field.TypeString, Unique: true, Comment: "for different biz"},
		{Name: "max_id", Type: field.TypeInt64, Comment: "current max id", Default: 1000},
		{Name: "step", Type: field.TypeInt64, Comment: "nums per batch", Default: 1000},
		{Name: "desc", Type: field.TypeString, Size: 255},
		{Name: "version", Type: field.TypeInt32, Comment: "version control", Default: 0},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
	}
	// LeafTable holds the schema information for the "leaf" table.
	LeafTable = &schema.Table{
		Name:       "leaf",
		Columns:    LeafColumns,
		PrimaryKey: []*schema.Column{LeafColumns[0]},
	}
	// ShortURLColumns holds the columns for the "short_url" table.
	ShortURLColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "primary key"},
		{Name: "biz_id", Type: field.TypeInt64, Comment: "refer to leaf id"},
		{Name: "origin", Type: field.TypeString, Comment: "current max id"},
		{Name: "short", Type: field.TypeInt64, Unique: true, Comment: "short url"},
		{Name: "visit", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
		{Name: "expired_at", Type: field.TypeInt64, Default: 0},
	}
	// ShortURLTable holds the schema information for the "short_url" table.
	ShortURLTable = &schema.Table{
		Name:       "short_url",
		Columns:    ShortURLColumns,
		PrimaryKey: []*schema.Column{ShortURLColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tshorturl_short_biz_id",
				Unique:  true,
				Columns: []*schema.Column{ShortURLColumns[3], ShortURLColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LeafTable,
		ShortURLTable,
	}
)

func init() {
	LeafTable.Annotation = &entsql.Annotation{
		Table: "leaf",
	}
	ShortURLTable.Annotation = &entsql.Annotation{
		Table: "short_url",
	}
}
